#!/bin/bash
#
# FILE: start_spyder
# DATE: 2 JAN 2023
# AUTH: G. E. Deschaines
# PROG: Shell script invoked in cartwheel-3d home directory.
# DESC: Script preparing shell environment and invoking Spyder IDE
#       bundled with Python 2 packages installed on Ubuntu 18.04 LTS
#       distributions, for working with Cartwheel-3d/Python project.

# Set path to Spyder (Python 2) exectuable
SPYDER_EXE=/usr/bin/spyder

# Set Cartwheel-3d home path if not already defined.
if [ "${CW3D_HOME}" == "" ]
then 
  CW3D_HOME=`/bin/pwd`
fi

# Set Cartwheel-3d target to ["Debug"|"Release"].
TARGET="Release"

# Pre-pend Cartwheel-3d target shared library path to the
# LD_LIBRARY_PATH environment variable.
LD_LIBRARY_PATH=${CW3D_HOME}/lib/${TARGET}:${LD_LIBRARY_PATH}

# Invoke Spyder IDE as a background process, then exit.
if [ -e "${CW3D_HOME}/Python/.spyproject/workspace.ini" ]
then
  $SPYDER_EXE --project="${CW3D_HOME}/Python" & 
else
  cd ./Python; $SPYDER_EXE &
fi

